FROM ubuntu:18.04

RUN apt-get update

RUN apt-get -y install curl

RUN curl -OL https://download.bitcoinsv.io/bitcoinsv/1.0.6/bitcoin-sv-1.0.6-x86_64-linux-gnu.tar.gz

RUN tar zxvf bitcoin-sv-1.0.6-x86_64-linux-gnu.tar.gz

WORKDIR /bitcoin-sv-1.0.6/

RUN ln -s /bitcoin-sv-1.0.6/bin/bitcoin-cli /bitcoin-cli

COPY bitcoin.conf /root/.bitcoin/bitcoin.conf

RUN mkdir -p /root/.bitcoin/regtest
COPY ./regtest_wallet.dat /root/.bitcoin/regtest/wallet.dat

ENTRYPOINT ["./bin/bitcoind", "-regtest",  "-printtoconsole"]
